import React from "react";
import { ShieldAlert, Heart, Activity } from "lucide-react";

export const Footer: React.FC = () => {
  return (
    <footer className="footer-wrapper">
      <div className="container footer-content">
        <div className="disclaimer-box">
          <div className="disclaimer-header">
            <ShieldAlert size={18} className="disclaimer-icon" />
            <span className="disclaimer-title">Clinical Disclaimer & Notice</span>
          </div>
          <p className="disclaimer-text">
            The screening assessments and predictions provided by AI Medical Diagnosis are generated by artificial intelligence models for investigative, educational, and clinical decision-support purposes only. They do NOT constitute a definitive medical diagnosis, prescription, or clinical judgment. Always consult a licensed healthcare professional for medical conditions and treatments.
          </p>
        </div>

        <div className="footer-bottom">
          <div className="footer-brand">
            <Activity size={18} color="#38bdf8" />
            <span>AI Medical Diagnosis Assistant</span>
            <span className="badge badge-cyan" style={{ fontSize: "0.6875rem", padding: "0.15rem 0.5rem" }}>
              v1.0.0
            </span>
          </div>

          <div className="footer-copyright">
            Built with <Heart size={14} color="#f43f5e" style={{ display: "inline", verticalAlign: "middle", margin: "0 2px" }} /> for Clinical AI Research
          </div>
        </div>
      </div>
    </footer>
  );
};
