import React from "react";
import { Link } from "react-router-dom";
import type { PredictionResponse } from "../types";
import { formatDate } from "../utils/formatters";
import {
  AlertTriangle,
  CheckCircle2,
  History,
  RotateCcw,
  Sparkles,
  ShieldAlert,
  Printer,
  Cpu,
} from "lucide-react";

interface PredictionResultCardProps {
  result: PredictionResponse;
  onReset: () => void;
}

export const PredictionResultCard: React.FC<PredictionResultCardProps> = ({
  result,
  onReset,
}) => {
  const isPositive = result.is_positive;
  const prob = result.probability ?? 0.5;
  const probPercent = (prob * 100).toFixed(1);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="prediction-result-card glass-card">
      {/* Result Header */}
      <div className="result-card-header">
        <div className="header-badge-row">
          <span className="badge badge-purple">
            <Cpu size={12} style={{ marginRight: "3px" }} />
            {result.model_type} ({result.model_version})
          </span>
          <span className="result-timestamp">{formatDate(result.timestamp)}</span>
        </div>

        <h2 className="result-disease-title">{result.disease_display_name} Screening Report</h2>
      </div>

      {/* Outcome Banner */}
      <div className={`outcome-banner ${isPositive ? "outcome-positive" : "outcome-negative"}`}>
        <div className="outcome-icon-badge">
          {isPositive ? (
            <AlertTriangle size={32} className="outcome-icon" />
          ) : (
            <CheckCircle2 size={32} className="outcome-icon" />
          )}
        </div>
        <div className="outcome-text-block">
          <div className="outcome-classification">{result.prediction_label}</div>
          <div className="outcome-subtext">
            {isPositive
              ? "Elevated statistical risk pattern identified across screening biometrics."
              : "No significant screening risk indicators detected based on submitted parameters."}
          </div>
        </div>
      </div>

      {/* Calibrated Probability Gauge */}
      {result.probability !== undefined && (
        <div className="probability-gauge-box">
          <div className="gauge-label-row">
            <span className="gauge-title">Calibrated Risk Probability</span>
            <span className="gauge-percentage">{probPercent}%</span>
          </div>

          <div className="gauge-track">
            <div
              className={`gauge-fill ${isPositive ? "fill-positive" : "fill-negative"}`}
              style={{ width: `${Math.min(100, Math.max(0, prob * 100))}%` }}
            />
          </div>

          <div className="gauge-footer-row">
            <span>Low Risk (0%)</span>
            {result.decision_threshold !== undefined && (
              <span className="threshold-marker">
                Decision Threshold: {(result.decision_threshold * 100).toFixed(0)}%
              </span>
            )}
            <span>High Risk (100%)</span>
          </div>
        </div>
      )}

      {/* AI Clinical Narrative Explanation */}
      {result.explanation && (
        <div className="explanation-section">
          <div className="section-subtitle-row">
            <Sparkles size={16} color="#38bdf8" />
            <span className="section-label">AI Decision Support Narrative</span>
          </div>
          <p className="explanation-paragraph">{result.explanation}</p>
        </div>
      )}

      {/* Evaluated Inputs Snapshot */}
      {result.metadata?.inputs && (
        <div className="inputs-snapshot-section">
          <h4 className="snapshot-title">Evaluated Biometric Features</h4>
          <div className="snapshot-grid">
            {Object.entries(result.metadata.inputs).map(([key, val]) => (
              <div key={key} className="snapshot-item">
                <span className="snapshot-key">{key}</span>
                <span className="snapshot-val">{String(val)}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Disclaimer */}
      <div className="result-disclaimer-note">
        <ShieldAlert size={16} className="disclaimer-mini-icon" />
        <span>
          {result.disclaimer ||
            "This screening report is generated by AI decision support and must be clinically correlated by a physician."}
        </span>
      </div>

      {/* Action Buttons */}
      <div className="result-actions-row">
        <button type="button" onClick={onReset} className="btn btn-secondary">
          <RotateCcw size={16} />
          <span>New Screening</span>
        </button>

        <button type="button" onClick={handlePrint} className="btn btn-secondary">
          <Printer size={16} />
          <span>Print / Save PDF</span>
        </button>

        <Link to="/history" className="btn btn-primary">
          <History size={16} />
          <span>View in History Log</span>
        </Link>
      </div>
    </div>
  );
};
