from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, field_validator


class DiseaseCategory(str, Enum):
    TABULAR = "tabular"
    IMAGE = "image"


class InputType(str, Enum):
    FORM = "form"
    IMAGE_UPLOAD = "image_upload"


class ModelFramework(str, Enum):
    SKLEARN = "scikit-learn"
    XGBOOST = "xgboost"
    TENSORFLOW = "tensorflow"
    PYTORCH = "pytorch"


class FeatureDataType(str, Enum):
    INTEGER = "int"
    FLOAT = "float"
    CATEGORICAL = "categorical"


class TabularFeatureSpec(BaseModel):
    name: str
    display_name: str
    data_type: FeatureDataType
    required: bool = True
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    unit: Optional[str] = None
    allowed_values: Optional[List[Union[int, float, str]]] = None
    value_descriptions: Optional[Dict[str, str]] = None


class ImageInputSpec(BaseModel):
    allowed_formats: List[str] = Field(default_factory=lambda: ["png", "jpg", "jpeg"])
    max_size_bytes: int = 10 * 1024 * 1024  # 10 MB default
    target_dimensions: List[int] = Field(default_factory=lambda: [224, 224])
    channels: int = 3


class DiseaseConfig(BaseModel):
    # 1. Identity
    id: str = Field(..., min_length=2, max_length=50)
    version: str = Field(..., min_length=1, max_length=20)
    is_active: bool = True

    # 2. Display Information
    display_name: str = Field(..., min_length=2, max_length=100)
    category: DiseaseCategory
    input_type: InputType
    short_description: str

    # 3. Model Information
    framework: ModelFramework
    model_type: str
    artifact_filename: str
    metadata_filename: Optional[str] = None

    # Base directory where model artifacts reside (resolved at load time)
    model_dir: Optional[str] = None

    # 4. Input Definition
    tabular_features: Optional[List[TabularFeatureSpec]] = None
    image_spec: Optional[ImageInputSpec] = None

    # 5. Preprocessing Strategy (Declarative)
    preprocessing: Dict[str, Any] = Field(default_factory=dict)

    # 6. Decision & Output Rules
    decision_threshold: float = Field(default=0.50, ge=0.0, le=1.0)
    positive_label: str
    negative_label: str
    supports_probability: bool = True

    # 7. Performance & Validation Metrics
    metrics: Dict[str, float] = Field(default_factory=dict)

    # 8. Safety & Compliance
    clinical_purpose: str = "Screening/research prototype only, not a definitive medical diagnosis."
    is_diagnostic_tool: bool = False
    disclaimer: str = (
        "This result is generated by an AI screening model and is not a medical diagnosis. "
        "Always consult a certified healthcare professional."
    )

    @field_validator("tabular_features")
    @classmethod
    def validate_tabular_inputs(cls, v, info):
        category = info.data.get("category")
        if category == DiseaseCategory.TABULAR and not v:
            raise ValueError("tabular_features must be provided for tabular disease category.")
        return v

    @field_validator("image_spec")
    @classmethod
    def validate_image_inputs(cls, v, info):
        category = info.data.get("category")
        if category == DiseaseCategory.IMAGE and not v:
            raise ValueError("image_spec must be provided for image disease category.")
        return v


class DiseasePublicInfo(BaseModel):
    id: str
    version: str
    display_name: str
    category: DiseaseCategory
    input_type: InputType
    short_description: str
    tabular_features: Optional[List[TabularFeatureSpec]] = None
    image_spec: Optional[ImageInputSpec] = None
    positive_label: str
    negative_label: str
    supports_probability: bool
    metrics: Dict[str, float]
    clinical_purpose: str
    disclaimer: str
