import React, { useEffect, useState } from "react";
import { useLocation, useParams, Link } from "react-router-dom";
import type { PredictionResponse } from "../types";
import { historyService } from "../services/historyService";
import { PredictionResult } from "../components/PredictionResult";
import {
  Activity,
  AlertCircle,
  ArrowLeft,
  Grid,
} from "lucide-react";

export const ResultPage: React.FC = () => {
  const location = useLocation();
  const { predictionId } = useParams<{ predictionId?: string }>();

  const [result, setResult] = useState<PredictionResponse | null>(
    (location.state as any)?.result || null
  );
  const [loading, setLoading] = useState<boolean>(!result && !!predictionId);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (result) return;

    if (predictionId) {
      const fetchHistoricalResult = async () => {
        try {
          setLoading(true);
          setError(null);
          const item = await historyService.getPredictionById(predictionId);
          // Map historical prediction item to standard PredictionResponse structure
          const mappedResponse: PredictionResponse = {
            disease_id: item.disease,
            disease_display_name: item.disease_display_name,
            prediction_label: item.result.prediction,
            is_positive: item.result.is_positive,
            probability: item.result.probability,
            decision_threshold: item.model.threshold,
            model_version: item.model.version,
            model_type: item.model.model_type,
            explanation: item.explanation,
            clinical_purpose: "Automated clinical decision support and patient risk assessment.",
            disclaimer: "This screening result is generated by AI decision-support models and does not represent a medical diagnosis.",
            metadata: item.metadata,
            timestamp: item.created_at,
          };
          setResult(mappedResponse);
        } catch (err: any) {
          setError(err?.message || `Failed to locate prediction record '${predictionId}'.`);
        } finally {
          setLoading(false);
        }
      };

      fetchHistoricalResult();
    }
  }, [predictionId, result]);

  if (loading) {
    return (
      <div className="container page-container">
        <div className="loading-state">
          <Activity className="spinner-icon pulse-animation" size={36} />
          <p>Retrieving diagnostic screening assessment...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="container page-container">
        <div className="error-alert" role="alert">
          <AlertCircle size={20} />
          <span>{error}</span>
        </div>
        <Link to="/dashboard" className="btn btn-secondary" style={{ marginTop: "1rem" }}>
          <ArrowLeft size={16} />
          <span>Return to Dashboard</span>
        </Link>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="container page-container" style={{ textAlign: "center", padding: "4rem 1.5rem" }}>
        <div className="glass-card" style={{ maxWidth: "540px", margin: "0 auto", padding: "3rem 2rem" }}>
          <div style={{ display: "inline-flex", padding: "1rem", borderRadius: "50%", background: "rgba(56, 189, 248, 0.1)", marginBottom: "1.5rem" }}>
            <Grid size={40} color="#38bdf8" />
          </div>
          <h2 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "0.5rem" }}>No Active Screening Result</h2>
          <p style={{ color: "var(--text-muted)", marginBottom: "2rem", lineHeight: 1.6 }}>
            Please select a disease module from the catalog to execute a screening and generate a diagnostic assessment.
          </p>
          <div style={{ display: "flex", gap: "1rem", justifyContent: "center" }}>
            <Link to="/dashboard" className="btn btn-secondary">
              Dashboard
            </Link>
            <Link to="/diseases" className="btn btn-primary">
              Explore Disease Catalog
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="container page-container">
      <div className="page-header" style={{ marginBottom: "1.5rem" }}>
        <Link to={`/predict/${result.disease_id}`} className="back-link">
          <ArrowLeft size={16} />
          <span>Back to {result.disease_display_name} Form</span>
        </Link>
      </div>

      <PredictionResult
        result={result}
        predictionId={predictionId || (location.state as any)?.predictionId || (result as any)?.id}
      />
    </div>
  );
};
